# Generated by Django 3.1.7 on 2021-04-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254)),
                ('second_name', models.CharField(max_length=254)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=254)),
                ('phone', models.IntegerField()),
                ('county', models.CharField(max_length=254)),
                ('town', models.CharField(max_length=254)),
            ],
        ),
    ]
