# Generated by Django 3.1.7 on 2021-04-29 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=254)),
                ('phone', models.IntegerField()),
                ('county', models.CharField(max_length=254)),
                ('town', models.CharField(max_length=254)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Medcine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('generic_name', models.CharField(max_length=254)),
                ('category', models.CharField(choices=[('liquid', 'liquid'), ('tablet', 'tablet'), ('capsules', 'capsules'), ('inhaler', 'inhalers'), ('injections', 'injections'), ('implants\\patches', 'implants\\patches'), ('ointment\\creams', 'ointment\\creams'), ('spray', 'spray'), ('drops', 'drops')], max_length=254)),
                ('shelf', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('manufacturer_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.manufacturer')),
            ],
        ),
    ]
