# Generated by Django 3.1.7 on 2021-04-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_manufacturer_medcine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medcine',
            new_name='Medicine',
        ),
    ]
