# Generated by Django 3.1.7 on 2021-04-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210429_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='strength',
            field=models.CharField(default='250mg', max_length=254),
            preserve_default=False,
        ),
    ]
