# Generated by Django 3.1.7 on 2021-05-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_medicine_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment',
            field=models.CharField(choices=[('cash', 'cash'), ('credit', 'credit')], default='cash', max_length=254),
            preserve_default=False,
        ),
    ]
