# Generated by Django 3.1.7 on 2021-05-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_customer_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=254)),
                ('phone', models.IntegerField()),
                ('county', models.CharField(max_length=254)),
                ('town', models.CharField(max_length=254)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
