# Generated by Django 3.1.7 on 2021-05-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
