# Generated by Django 3.1.7 on 2021-05-04 03:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210504_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_no',
            field=models.AutoField(default='01', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
