# Generated by Django 3.1.7 on 2021-05-04 05:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20210504_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('date_of_purchase', models.DateField(auto_created=True, null=True)),
                ('purchase_no', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('box_quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VAT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Mpesa', 'Mpesa')], max_length=254)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], max_length=254)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.manufacturer')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.medicine')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.supplier')),
            ],
        ),
    ]
